notifications:
  email: false
  slack:
    secure: y/pbvuF7MK62XOkQaiD1lr6E7dgcNoYOFlzbn6zdL2kJsAYItm05emhqWcge01Rz8Hjgwh17xY4HqSFZa90NL8vj8IS61E+USpfl7TXEnsG2LMel0aX48gQKQZauyZ38l7UoCvJ1tX5i5Ar67AggGgkzlANEerN0Zm9UCDIn4ffOItWcKRufBL1iez17JV4aa1y7Ox5d0SqIqQdE4xmLuf9mSGOtQeitpq/qLVpPx0R60CQPM9Xd0+IRnXy9x337pyZfzIqPF6ta8fO48hg+AyX//lY3PBXDgNF7HzZel3q1C8jFVAXX6HEPfewzDnWm7ENb+AIvnyuUwoFoqA5rf9VfDxl0/aoM4VSAUSC6QNzuHlT4+P2rjJwNDw26/OJgxdp0XJ+zdYEuj87lis7b9fBADS3uMElaZRm3DnJCNBmF3wsLI5a5G6wNvZkOn2jhZelVLJw4NaB6Cy6395SNzn79Jur7XcKUVo391gdDt3EI296ILQ5v6McW+MaNQGhbiUotOtUi+Il4g8YpyTQoDHcm+8iHh3fub6tuuHRvED8zEl5JdexqaqXjoDaP2/WgDG5vk74KdyDOVWDaDDT+JOb7t7qwIeVKhhdDa/kYi61ts4TbiFORSyudkDUEyBWpj+ZztTzrTT8chx3ndDZBvKGXvm/msdOM3QLZpONzE3s=
language: go
go:
- '1.10'
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
